### ISSUE TITLE
环境暗的时候怎样让闪光灯亮着，不是拍的时候亮。类似暗处扫二维码时候开闪光灯

### ISSUE THREAD

**Issue by helloworld10010** [Shouheng88/iCamera#2]

**Comment by Shouheng88** [comment]
有个提示的还没加，可以做到的

**Comment by Shouheng88** [comment]
这种东西应该在相机本身功能之外了，你看下闪光灯是怎么打开的，支付宝扫描也是用户手动点击才能开启闪光灯的，虽然说我们可以通过实时的环境来判断当前是否需要设置闪光灯，但是这样用户体验也不好，还是让用户主动去做，关于实时预览的问题，我后续处理下

**Comment by Shouheng88** [comment]
参考 [CameraActivity](https://github.com/Shouheng88/iCamera/blob/feature/v0.1.1/sample/app/src/main/java/me/shouheng/icamerasample/activity/CameraActivity.kt) 的暗处的灯光提示
