### ISSUE TITLE
camera2的缩放使用这个代码

### ISSUE THREAD

**Issue by ioveBean** [Shouheng88/iCamera#7]
在camera2Manager中的captureStillPicture中更改 
//   setZoomInternal();
                // 预览如果有放大，拍照的时候也应该保存相同的缩放
                Rect zoomRect = previewRequest.get(CaptureRequest.SCALER_CROP_REGION);
                if (zoomRect != null) {
                    captureBuilder.set(CaptureRequest.SCALER_CROP_REGION, zoomRect);
                }
这个人写的解决了这个问题,https://blog.csdn.net/afei__/article/details/86710164
这个人很厉害,所有问题似乎基本从他的代码里解决了,包括照片的方向问题;

**Comment by Shouheng88** [comment]
好的，有空看下

**Comment by oudengding** [comment]
预览的缩放级别是1.0，但我用起来还是感觉被放大了一些，这会是什么原因呢？ @Shouheng88

**Comment by Shouheng88** [comment]
缩放的问题解决了，其实很简单，就是 CaptureRequest.Builder 对象，预览的和拍摄的不是同一个，对拍摄的也按照当前的设置赋值一下就行了，很简单～
