### ISSUE TITLE
camera1拍摄的NV21格式的图片，怎么存储为JPEG格式呢

### ISSUE THREAD

**Issue by RookieExaminer** [Shouheng88/iCamera#9]
因为低版本的手机上拍照的照片，可能只有NV21格式的，那么如何更好保存呢，YuvImage进行解压处理NV21的话，低版本还会有内存泄漏。 希望可以解答一下 感谢  
网上的方法是用libjpeg.奈何实在不会
https://blog.csdn.net/q979713444/article/details/80446404

**Comment by Shouheng88** [comment]
代码里拍摄默认输出是 JPEG

**Comment by Shouheng88** [comment]
这个新版本的方法中有一些转换的方法，可以参考下 [ImageHelper](https://github.com/Shouheng88/iCamera/blob/feature/v0.1.1/icamera/src/main/java/me/shouheng/icamera/util/ImageHelper.java)，另外可以下载新版本的 demo 体验下预览效果
